config/routes.rb
Paradime::Application.routes.draw do
  devise_for :users, path_names: { sign_up: 'register', sign_in: 'sign-in', sign_out: 'sign-out' }
  
  match '/listings/manage',  to: 'listings#manage'
  resources :listings do
    collection do
      match 'search' => 'listings#index', via: [:get], as: :search
    end
  end

  root to: 'static_pages#home'
  
  match '/how-it-works',  to: 'static_pages#how_it_works', as: '/how_it_works'
  match '/who-we-are',    to: 'static_pages#who_we_are', as: '/who_we_are'
end

app/models/attachment.rb
class Attachment < ActiveRecord::Base
  attr_accessible :attachable_id, :file, :title
  
  belongs_to :attachable, polymorphic: true
  
  # Mounts the file uploader to this model.
  mount_uploader :file, FileUploader
  
  validates_length_of :title, maximum: 500
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :label
  
  belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  attr_accessible :user_id, :title, :price, :city, :state, :show_email, :email, :show_phones, :primary_phone, :secondary_phone, :description, :listing_owner, :ip_at_creation, :ip_at_modification, :attachments_attributes

  geocoded_by :location
  
  before_validation :format_phones
  after_validation :geocode, :if =>  lambda { |l| l.city_changed? || l.state_changed? }

  UNRANSACKABLE_ATTRIBUTES = ["id", "show_email", "email", "show_phones", "primary_phone", "secondary_phone", "listing_owner", "ip_at_creation", "ip_at_modification", "updated_at", "user_id"]
  
  belongs_to :user
  has_many :categories
  has_many :attachments, :as => :attachable, dependent: :destroy
  
  accepts_nested_attributes_for :attachments, :allow_destroy => true
  
  validates_presence_of :category_id, :title, :price, :city, :state, :description, :listing_owner
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, format: { with: VALID_EMAIL_REGEX }
  validates_length_of :title, maximum: 500
  validates_length_of :city, maximum: 250
  validates_length_of :email, :primary_phone, :secondary_phone, :listing_owner, maximum: 250
  validates_length_of :description, maximum: 9000
  
  def format_phones
    primary_phone = self.primary_phone.gsub(/\D/,'')
    secondary_phone = self.secondary_phone.gsub(/\D/,'')
  end
  
  def self.ransackable_attributes auth_object = nil
    (column_names - UNRANSACKABLE_ATTRIBUTES) + _ransackers.keys
  end
  
  def location
  	[city, state].join(', ')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :name, :password, :password_confirmation, :remember_me, :admin
  
  has_many :listings, dependent: :destroy
  
  validates_presence_of :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout :layout_by_resource
  
  def after_sign_in_path_for(resource)
    listings_manage_path
  end

  protected
  
  def layout_by_resource
    if (controller_name == 'sessions' || controller_name == 'registrations' || controller_name == 'passwords') && (action_name == 'new' || action_name == 'create' )
      "alternate"
    else
      "application"
    end
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  
  def index
  	if params[:location].present? && params[:within].present? && (params[:within].to_i > 0)
	  @search = Listing.near(params[:location],params[:within], order: :distance).search(params[:q])
    else
      @search = Listing.search(params[:q])
    end
    @listings = @search.result.paginate(page: params[:page], per_page: 20, joins: "LEFT OUTER JOIN attachments ON listings.id = attachments.attachable_id", select: "listings.*, COUNT(attachments.id) AS photos", group: "listings.id", order: "listings.created_at DESC, listings.title ASC, listings.id DESC")
    @categories = Category.find(:all, :select => "id, label", order: "label ASC").collect
  end
  
  def manage
    @listings = Listing.paginate(page: params[:page], per_page: 20, joins: "LEFT OUTER JOIN attachments ON listings.id = attachments.attachable_id", select: "listings.*, COUNT(attachments.id) AS photos", conditions: ["user_id = ?", current_user.id], group: "listings.id", order: "listings.created_at DESC, listings.title ASC, listings.id DESC")
  end
  
  def show
    @listing = Listing.find(params[:id])
    @listing_attachments = Attachment.find(:all, conditions: ["attachable_id = ?", params[:id]], order: "id ASC, title ASC")
  end
  
  def new
    @listing = Listing.new
    @categories = Category.find(:all, :select => "id, label", order: "label ASC").collect
  end
  
  def create
    @listing = Listing.new(params[:listing])
    @listing.user_id = current_user.id
    if @listing.save
      flash[:success] = "Your new listing has been published!"
      redirect_to listing_path(@listing)
    else
      render 'new'
    end
  end
  
  def edit
    @listing = Listing.find(params[:id])
    @categories = Category.find(:all, :select => "id, label", order: "label ASC").collect
    if @listing.user_id == current_user.id
      # current user is the owner of this listing
    else
      flash[:error] = "You are not authorized to update the listing!"
      redirect_to listings_path
    end
  end
  
  def update
    @listing = Listing.find(params[:id])
    if @listing.user_id == current_user.id
      if @listing.update_attributes(params[:listing])
	    redirect_to @listing, :notice  => "Your listing has been updated!"
	  else
	    render 'edit'
	  end
    else
      flash[:error] = "You are not authorized to update the listing!"
      redirect_to listings_path
    end
  end
  
  def destroy
    @listing = Listing.find(params[:id])
    if @listing.user_id == current_user.id
   	  @listing.destroy
      redirect_to listings_manage_path, :notice => "Your listing has been successfully removed."
    else
      flash[:error] = "You are not authorized to delete the listing!"
      redirect_to listings_manage_path
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def who_we_are
  end
  
  def how_it_works
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Paradime"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/listings_helper.rb
module ListingsHelper
  def us_states
      [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
      ]
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<div class="container">
		<small>
			&copy; 2013 Copyright <%= link_to "Paradime", root_path %> | All Rights Reserved
		</small>
		<nav>
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Who We Are", who_we_are_path %></li>
				<li><%= link_to "How it Works", how_it_works_path %></li>
			</ul>
		</nav>
		<%= debug(params) if Rails.env.development? %>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar">
	<div class="container">
		<%= link_to "Paradime", root_path, class: "logo" %>
		<ul class="nav nav-pills pull-right">
			<li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "Home", root_path %></li>
			<li class="<%= 'active' if current_page?(who_we_are_path) %>"><%= link_to "Who We Are", who_we_are_path %></li>
			<li class="<%= 'active' if current_page?(how_it_works_path) %>"><%= link_to "How it Works", how_it_works_path %></li>
			<li class="<%= 'active' if current_page?(listings_path) %>"><%= link_to "View Listings", listings_path %></li>
			<li id="fat-menu" class="dropdown">
				<% if user_signed_in? %>
					<a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= "#{current_user.name}" %> <b class="caret"></b></a>
				<% else %>
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">Members <b class="caret"></b></a>
				<% end %>
				<ul class="dropdown-menu">
					<% if user_signed_in? %>
						<li><%= link_to "New Listing", new_listing_path %></li>
						<li><%= link_to "Manage Listings", listings_manage_path %></li>
						<li><%= link_to "Profile", edit_user_registration_path %></li>
		                <li class="divider"></li>
						<li><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
	    	        <% else %>
	    	        	<li><%= link_to "Register", new_user_registration_path %></li>
		                <li class="divider"></li>
	    	        	<li><%= link_to "Sign In", new_user_session_path %></li>
	    	        <% end %>
	            </ul>
			</li>
		</ul>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/alternate.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <div class="container no-top-border">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>    
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
		</div>
		<%= render 'layouts/footer' %>
	</body>
</html>

app/views/listings/_advanced_search.html.erb
<div class="advanced-search well">
	<div class="advanced-search-toggle" data-toggle="collapse" data-target="#advanced_search">
		<h4>Advanced Search</h4> 
	</div>
	<div id="advanced_search" class="collapse <%= "in" if params['q'] %>">
		<%= search_form_for @search do |f| %>
			<div class="search-fields">
				<div class="search-field search-category">
					<%= f.label :category_id, "Category" %>
					<%= f.select :category_id_eq, options_for_select(@categories.each { |c| [ c.label, c.id ] }, selected: @search.category_id_eq), { include_blank: 'Select a Category' } %>
				</div>
				<div class="search-field search-title">
					<%= f.label :title_cont, "Title Contains" %>
					<%= f.text_field :title_cont, placeholder: "Title", class: "input-xxlarge" %>
				</div>
				<div class="search-field search-description">
					<%= f.label :description_cont, "Description Contains" %>
					<%= f.text_field :description_cont, placeholder: "Description", class: "input-xxlarge" %>
				</div>
				<div class="search-field search-price-range">
					<%= f.label :price_gteq, "Price Range" %>
					<%= f.text_field :price_gteq, placeholder: "Minimum", class: "input-medium" %>
					<%= f.label :price_lteq, " - " %>
					<%= f.text_field :price_lteq, placeholder: "Maximum", class: "input-medium" %>
				</div>
				<div class="search-field search-location">
					<%= f.label :location, "Search in" %>
					<%= text_field_tag :location, params[:location], placeholder: "City, State", class: "input-xlarge" %>
					<%= f.label :within, "within" %>
					<%= number_field_tag :within, params[:within], placeholder: "50", class: "input-small" %> <strong>miles</strong>
				</div>
				<div class="search-actions">
					<%= f.submit "Search", class: "btn btn-success btn-medium" %>
				</div>
				<div class="search-sort-by">
					Sort by <%= sort_link @search, :title %> | <%= sort_link @search, :price %> | <%= sort_link @search, :created_at, "Date Listed" %>
				</div>
			</div>
		<% end %>
		<div class="clearfix"></div>
	</div>
</div>

app/views/listings/_form.html.erb
<%= nested_form_for @listing, html: { multipart: true } do |f| %>
	<%= render 'shared/error_messages', :object => @listing %>
	<div>
		<%= f.label :category_id, "Category*" %>
		<%= f.select :category_id, options_for_select(@categories.each { |c| [ c.label, c.id ] }, selected: @listing.category_id), { include_blank: 'Select a Category' } %>
	</div>
	<div>
		<%= f.label :title, "Title*" %>
		<%= f.text_field :title, placeholder: "Listing Title", class: "input-massive" %>
	</div>
	<div>
		<%= f.label :price, "Price*" %>
		<div class="input-prepend">
			<span class="add-on dollar">$</span><%= f.text_field :price, class: "input-with-icon input-medium", placeholder: "0.00" %>
		</div>
	</div>
	<div>
		<%= f.label :city, "City* (this is required to make it easier for users to find your listing)" %>
		<%= f.text_field :city, class: "input-xlarge", placeholder: "City" %>
	</div>
	<div>
		<%= f.label :state, "State* (this is required to make it easier for users to find your listing)" %>
		<%= f.select :state, us_states %>
	</div>
	<div>
		<%= f.label :email, "Contact Email" %>
		<%= f.email_field :email, placeholder: "email@domain.com", class: "input-large" %>
	</div>
	<div>
		<%= f.check_box :show_email %> <%= f.label :show_email, "Make email visible?", class: "inline-input-label" %>
		<br /><br />
	</div>
	<div>
		<%= f.label :primary_phone, "Primary Phone" %>
		<%= f.text_field :primary_phone, placeholder: "(555) 555-5555", class: "input-large", value: (number_to_phone(f.object.primary_phone, :area_code => true)) %>
	</div>
	<div>
		<%= f.label :secondary_phone, "Secondary Phone" %>
		<%= f.text_field :secondary_phone, placeholder: "(555) 555-5555", class: "input-large", value: (number_to_phone(f.object.primary_phone, :area_code => true)) %>
	</div>
	<div>
		<%= f.check_box :show_phones %> <%= f.label :show_phones, "Make phones visible?", class: "inline-input-label" %>
		<br /><br />
	</div>
	<div>
		<%= f.label :description, "Description*" %>
		<%= f.text_area :description, class: "tinymce" %>
	</div>
	<div class="listing-attachments">
		<h3>Attached Images</h3>
		<%= f.fields_for :attachments do |a| %>
			<div class="row image-preview">
				<% if a.object.file? %>
					<%= a.label :file, "Current Image Preview" %>
					<%= link_to image_tag(a.object.file.url, alt: a.object.title), a.object.file.url, title: a.object.title, class: "fancybox", rel: "group" %>
				<% end %>
			</div>
			<div class="row">
				<% if form_type == "new" %>
					<%= a.label :file, "Upload Image" %>
				<% else %>
					<%= a.label :file, "Replace Image" %>
				<% end %>
				<%= a.file_field :file %>
			</div>
			<div class="row">
				<%= a.label :title, "Caption" %>
				<%= a.text_field :title, placeholder: "Image Caption", class: "input-massive" %>
			</div>
			<div class="row">
				<%= a.link_to_remove "Remove Image", class: "btn btn-small btn-danger" %>
			</div>
		<% end %>
		<%= f.link_to_add "Add Image", :attachments, class: "btn btn-small btn-success add-attachment" %>
	</div>
	<div>
		<%= f.hidden_field :listing_owner, value: "#{current_user.email}" %>
		<%= f.hidden_field :ip_at_creation, value: "#{current_user.current_sign_in_ip}" %>
		<% if form_type == "new" %>
			<%= f.submit "Publish Listing", class: "btn btn-success" %>
		<% else %>
			<%= f.submit "Update Listing", class: "btn btn-success" %>
		<% end %>
		<div class="btn-cancel">
			<%= link_to "Cancel", :back %>
		</div>
	</div>
<% end %>

app/views/listings/_listings.html.erb
<%= will_paginate %>
	<section class="listings-list">
		<% @listings.each do |listing| %>
			<article>
				<a class="listing" href="<%= listing_path(listing) %>">
					<div class="listing-title">
						<% if listing.photos.to_i == 1 %>
							<div class="listing-photo">
								<%= image_tag("photo.png") %>
							</div>
						<% elsif listing.photos.to_i > 2 %>
							<div class="listing-photo">
								<%= image_tag("photos.png") %>
							</div>
						<% end %>
						<%= listing.title %> <span class="listing-price">(<%= number_to_currency(listing.price, :unit => '$') %>)</span> <span class="listing-location"><%= "#{listing.city}, #{listing.state}" %></span>
					</div>
					<div class="listing-date">
						<%= time_ago_in_words(listing.created_at) %> ago
					</div>
				</a>
			</article>
		<% end %>
	</section>
<%= will_paginate %>

app/views/listings/_my_listings.html.erb
<%= will_paginate %>
	<section class="manage-listings-list">
		<% @listings.each do |listing| %>
			<article>
				<div class="manage-listing-title">
					<a class="manage-listing" href="<%= listing_path(listing) %>">
						<% if listing.photos.to_i == 1 %>
							<div class="manage-listing-photo">
								<%= image_tag("photo.png") %>
							</div>
						<% elsif listing.photos.to_i > 2 %>
							<div class="manage-listing-photo">
								<%= image_tag("photos.png") %>
							</div>
						<% end %>
						<%= listing.title %> <span class="manage-listing-price">(<%= number_to_currency(listing.price, :unit => '$') %>)</span>
					</a>
				</div>
				<div class="manage-listing-actions">
					<%= link_to "Update", edit_listing_path(listing), class: "btn btn-warning btn-small" %>
					<%= link_to "Delete", listing, method: :delete, data: { confirm: "Are you sure you want to delete this listing? (cannot be reversed)" }, class: "btn btn-danger btn-small" %>
				</div>
				<div class="manage-listing-date">
					<%= time_ago_in_words(listing.created_at) %> ago
				</div>
			</article>
		<% end %>
	</section>
<%= will_paginate %>

app/views/listings/edit.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox({
			padding		: 0,
			preload		: 5
		});
	});
</script>

<%= tinymce theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,forecolor,separator,bullist,numlist,outdent,indent,separator,undo,redo,separator,removeformat,code,fullscreen", theme_advanced_buttons2: "", theme_advanced_buttons3: "", width: "100%", height: "600", content_css: "/assets/tinymce.css", valid_elements: "-strong,-em,-u,-p,p[style],-ol,ol[style],-ul,ul[style],-li,li[style],-span,span[style],-div,div[style]", theme_advanced_resizing: true, theme_advanced_resize_horizontal: false %>

<% provide(:title, 'Update Listing') %>

<h2>Update Listing</h2>

<%= render partial: 'form', locals: { form_type: "edit" } %>

app/views/listings/index.html.erb
<% provide(:title, 'Listings') %>

<h1>Listings</h1>

<%= render 'advanced_search'%>

<% if @listings.empty? %>
	<h2>Nothing has been listed yet.</h2>
<% else %>
	<div id="listings">
		<%= render 'listings' %>
	</div>
<% end %>

app/views/listings/manage.html.erb
<% provide(:title, 'Manage Listings') %>

<h1>Manage Listings</h1>

<% if @listings.empty? %>
	<h2>You have not listed anything yet.</h2>
<% else %>
	<div id="listings">
		<%= render 'my_listings' %>
	</div>
<% end %>

app/views/listings/new.html.erb
<%= tinymce theme_advanced_buttons1: "bold,italic,underline,strikethrough,separator,forecolor,separator,bullist,numlist,outdent,indent,separator,undo,redo,separator,removeformat,code,fullscreen", theme_advanced_buttons2: "", theme_advanced_buttons3: "", width: "100%", height: "600", content_css: "/assets/tinymce.css", valid_elements: "-strong,-em,-u,-p,p[style],-ol,ol[style],-ul,ul[style],-li,li[style],-span,span[style],-div,div[style]", theme_advanced_resizing: true, theme_advanced_resize_horizontal: false %>

<% provide(:title, 'Create Listing') %>

<h2>Create Listing</h2>

<%= render partial: 'form', locals: { form_type: "new" } %>

app/views/listings/show.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$(".fancybox").fancybox({
			padding		: 0,
			preload		: 5
		});
	});
</script>

<% provide(:title, "Listing: #{@listing.title}") %>

<h1><%= @listing.title %></h1>

<div class="update-listing">
	<% if current_user && @listing.user_id == current_user.id %>
		<%= link_to "Update Listing", edit_listing_path(@listing), class: "btn btn-large btn-warning" %>
	<% end %>
</div>

<section class="listing-details">
	<div class="listing-price">
		Price: <%= number_to_currency(@listing.price, :unit => '$') %>
	</div>
	<div class="listing-location">
		<h3>Location</h3>
		<%= "#{@listing.city}, #{@listing.state}" %>
	</div>
	<div class="contact-details">
		<%= "<h3>Contact Information</h3>".html_safe if @listing.show_email? || @listing.show_phones? %>
		<div class="contact-email">
			<%= "<strong>Email:</strong> #{@listing.email}".html_safe if @listing.show_email? %>
		</div>
		<div class="contact-phones">
			<% if @listing.show_phones? %>
				<%= "<strong>Primary Number:</strong> #{number_to_phone(@listing.primary_phone, :area_code => true)}".html_safe if @listing.primary_phone? %>
				<br />
				<%= "<strong>Secondary Number:</strong> #{number_to_phone(@listing.primary_phone, :area_code => true)}".html_safe if @listing.secondary_phone? %>
			<% end %>
		</div>
	</div>
	<div class="listing-description">
		<h3>Description</h3>
		<%= @listing.description.html_safe %>
	</div>
</section>
<% if !@listing_attachments.empty? %>
	<section class="listing-attachments well">
		<div class="listing-attachments-toggle" data-toggle="collapse" data-target="#listing_attachments">
			<h2>
				Listing Images
			</h2>
		</div>
		<div id="listing_attachments" class="collapse">
			<div class="note">
				(click image to see original size)
			</div>
			<% @listing_attachments.each do |a| %>
				<div class="attachment">
					<%= link_to image_tag(a.file.url, alt: a.title), a.file.url, title: a.title, class: "fancybox", rel: "group" %>
				</div>
			<% end %>
		</div>
	</section>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<section id="error_explanation">
		<div class="alert alert-error">
			Oops! Your form has <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</section>
<% end %>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<h1>Paradime</h1>
	<h2>
		Think different. Sell different.
	</h2>
	<% if user_signed_in? %>
		<%= link_to "Post a new listing!", new_listing_path, class: "btn btn-large btn-success" %>
	<% else %>
		<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-large btn-success" %>
	<% end %>
</div>